apiVersion: v1
appVersion: "1.0"
description: Config for FDK informationmodel harvester etl
name: fdk-informationmodel-harvester-etl
version: 0.1.0
home: https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester-etl